#!/bin/bash
# generate-upgrade-sql.sh — Generate a SQL upgrade script for a V7→V8 site migration
# Usage: bash generate-upgrade-sql.sh [project_root] [removed_plugins_comma_separated]
#
# Reads the POM to find active plugins, then generates SQL to:
# 1. Activate remaining plugins in core_datastore
# 2. Clean up removed plugins (rights, roles, portlet types, dashboards, datastore)
# 3. Drop orphan tables from removed plugins
#
# Output: SQL script to stdout (redirect to file)

set -euo pipefail

PROJECT_ROOT="${1:-.}"
REMOVED_PLUGINS="${2:-}"

cd "$PROJECT_ROOT"

if [ ! -f "pom.xml" ]; then
    echo "-- ERROR: No pom.xml found in $PROJECT_ROOT" >&2
    exit 1
fi

# ============================================================
# Extract active plugins from POM
# ============================================================
ACTIVE_PLUGINS=$(python3 -c "
import xml.etree.ElementTree as ET
import re

tree = ET.parse('pom.xml')
root = tree.getroot()
ns = {'m': 'http://maven.apache.org/POM/4.0.0'}

deps = root.findall('.//m:dependency', ns)
if not deps:
    deps = root.findall('.//dependency')

plugins = []
for dep in deps:
    aid = dep.find('m:artifactId', ns) if dep.find('m:artifactId', ns) is not None else dep.find('artifactId')
    typ = dep.find('m:type', ns) if dep.find('m:type', ns) is not None else dep.find('type')
    gid = dep.find('m:groupId', ns) if dep.find('m:groupId', ns) is not None else dep.find('groupId')

    if aid is None:
        continue
    a = aid.text or ''
    t = typ.text if typ is not None else 'jar'
    g = gid.text if gid is not None else ''

    # Skip non-plugin dependencies (starters, BOM, themes, core)
    if 'starters' in g or 'themes' in g:
        continue
    if a in ('lutece-core', 'lutece-bom'):
        continue

    # Extract plugin name from artifactId
    name = a
    # plugin-xxx → xxx
    if name.startswith('plugin-'):
        name = name[7:]
    # library-xxx → xxx
    elif name.startswith('library-'):
        name = name[8:]
    # module-xxx-yyy → xxx-yyy (keep full module name)
    elif name.startswith('module-'):
        name = name[7:]

    if name and t in ('lutece-plugin', 'jar'):
        plugins.append(name)

for p in sorted(set(plugins)):
    print(p)
" 2>/dev/null)

# ============================================================
# Generate SQL
# ============================================================

cat <<'HEADER'
-- =============================================================
-- Lutece V7 → V8 Migration — Database Upgrade Script
-- Generated by lutece-migration-site-v8 skill
-- =============================================================
--
-- INSTRUCTIONS:
-- 1. Review this script carefully before executing
-- 2. Back up the database first: mysqldump -u USER -p DB_NAME > backup.sql
-- 3. Execute against the target database
-- 4. Restart the application after execution
--
-- =============================================================

SET NAMES utf8mb4;

HEADER

# --- Part 1: Activate remaining plugins ---
echo "-- ============================================================="
echo "-- PART 1: Activate remaining plugins in core_datastore"
echo "-- ============================================================="
echo ""

if [ -n "$ACTIVE_PLUGINS" ]; then
    echo "INSERT INTO core_datastore (entity_key, entity_value) VALUES"
    FIRST=true
    while IFS= read -r plugin; do
        [ -z "$plugin" ] && continue
        if [ "$FIRST" = true ]; then
            FIRST=false
        else
            echo ","
        fi
        printf "    ('core.plugins.status.%s.installed', 'true'),\n" "$plugin"
        printf "    ('core.plugins.status.%s.pool', 'portal')" "$plugin"
    done <<< "$ACTIVE_PLUGINS"
    echo ""
    echo "ON DUPLICATE KEY UPDATE entity_value = VALUES(entity_value);"
    echo ""
else
    echo "-- No active plugins detected in POM"
    echo ""
fi

# --- Part 2: Clean up removed plugins ---
if [ -n "$REMOVED_PLUGINS" ]; then
    echo ""
    echo "-- ============================================================="
    echo "-- PART 2: Clean up removed plugins"
    echo "-- ============================================================="
    echo ""

    IFS=',' read -ra REMOVED_ARRAY <<< "$REMOVED_PLUGINS"
    for plugin in "${REMOVED_ARRAY[@]}"; do
        plugin=$(echo "$plugin" | xargs)  # trim whitespace
        [ -z "$plugin" ] && continue

        echo "-- --- Cleanup: $plugin ---"
        echo ""

        # Deactivate plugin in datastore
        echo "-- Deactivate plugin"
        echo "DELETE FROM core_datastore WHERE entity_key = 'core.plugins.status.${plugin}.installed';"
        echo "DELETE FROM core_datastore WHERE entity_key = 'core.plugins.status.${plugin}.pool';"
        echo ""

        # Clean admin rights
        echo "-- Clean admin rights"
        echo "DELETE FROM core_user_right WHERE id_right IN (SELECT id_right FROM core_admin_right WHERE plugin_name = '${plugin}');"
        echo "DELETE FROM core_admin_right WHERE plugin_name = '${plugin}';"
        echo ""

        # Clean admin roles
        echo "-- Clean admin roles"
        echo "DELETE FROM core_admin_role_resource WHERE role_key IN (SELECT role_key FROM core_admin_role WHERE role_key LIKE '${plugin}%');"
        echo "DELETE FROM core_admin_role WHERE role_key LIKE '${plugin}%';"
        echo ""

        # Clean portlet types
        echo "-- Clean portlet types"
        echo "DELETE FROM core_portlet_type WHERE plugin_name = '${plugin}';"
        echo ""

        # Clean dashboards
        echo "-- Clean dashboards"
        echo "DELETE FROM core_dashboard WHERE dashboard_name LIKE '${plugin}%';"
        echo "DELETE FROM core_admin_dashboard WHERE dashboard_name LIKE '${plugin}%';"
        echo ""

        # Clean datastore (plugin-specific keys)
        # PROTECTED KEYS: never delete theme.globalThemeCode, portal.theme.*, core.*
        echo "-- Clean datastore (plugin-specific properties)"
        echo "-- WARNING: Do NOT delete theme.globalThemeCode, portal.theme.*, core.* keys"
        echo "DELETE FROM core_datastore WHERE entity_key LIKE '${plugin}.%'"
        echo "    AND entity_key NOT LIKE 'theme.globalThemeCode'"
        echo "    AND entity_key NOT LIKE 'portal.theme.%'"
        echo "    AND entity_key NOT LIKE 'core.%';"
        echo ""

        # Drop plugin tables (commented out — must be reviewed manually)
        echo "-- Drop plugin tables (REVIEW MANUALLY before uncommenting)"
        echo "-- Tables for plugin '${plugin}' — uncomment after verification:"
        echo "-- DROP TABLE IF EXISTS ${plugin}_*;  -- Replace with actual table names"
        echo ""
    done
else
    echo ""
    echo "-- ============================================================="
    echo "-- PART 2: Clean up removed plugins"
    echo "-- ============================================================="
    echo "-- No removed plugins specified. Pass them as second argument:"
    echo "-- bash generate-upgrade-sql.sh . \"plugin1,plugin2,plugin3\""
    echo ""
fi

# --- Part 3: Protected keys reminder ---
echo ""
echo "-- ============================================================="
echo "-- REMINDER: Protected datastore keys (NEVER delete these)"
echo "-- ============================================================="
echo "-- theme.globalThemeCode   — Used by ThemeDAO.getGlobalTheme(), NOT by plugin-theme"
echo "-- portal.theme.*          — Core theme configuration"
echo "-- core.*                  — Core system configuration"
echo "-- core.plugins.status.*   — Plugin activation (only delete for removed plugins)"
echo ""

echo "-- ============================================================="
echo "-- END OF MIGRATION SCRIPT"
echo "-- ============================================================="
